/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace InsuranceTypes {
      
    export type ClaimStruct = {id: BigNumberish, policyId: BigNumberish, amount: BigNumberish, submitted: boolean, accidentVerified: boolean, approved: boolean, paid: boolean}

    export type ClaimStructOutput = [id: bigint, policyId: bigint, amount: bigint, submitted: boolean, accidentVerified: boolean, approved: boolean, paid: boolean] & {id: bigint, policyId: bigint, amount: bigint, submitted: boolean, accidentVerified: boolean, approved: boolean, paid: boolean }
  
    }

  export interface ClaimManagerInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "INSURANCE_COMPANY_ROLE" | "ORACLE_ROLE" | "PAUSER_ROLE" | "approveClaim" | "authorizeClaim" | "getClaim" | "getPendingClaim" | "getRoleAdmin" | "grantRole" | "hasRole" | "insurancePolicy" | "insurancePool" | "isClaimRejected" | "pause" | "paused" | "rejectClaim" | "renounceRole" | "revokeRole" | "submitClaim" | "submitClaimFor" | "supportsInterface" | "unpause" | "verifyAccident"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ClaimApproved" | "ClaimAuthorized" | "ClaimRejected" | "ClaimSubmitted" | "EmergencyPaused" | "EmergencyUnpaused" | "Paused" | "PayoutCompleted" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'INSURANCE_COMPANY_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ORACLE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveClaim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'authorizeClaim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getClaim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPendingClaim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'insurancePolicy', values?: undefined): string;
encodeFunctionData(functionFragment: 'insurancePool', values?: undefined): string;
encodeFunctionData(functionFragment: 'isClaimRejected', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'rejectClaim', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'submitClaim', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitClaimFor', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifyAccident', values: [BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'INSURANCE_COMPANY_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ORACLE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizeClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'insurancePolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'insurancePool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isClaimRejected', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitClaimFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyAccident', data: BytesLike): Result;
  }

  
    export namespace ClaimApprovedEvent {
      export type InputTuple = [claimId: BigNumberish, approvedBy: AddressLike];
      export type OutputTuple = [claimId: bigint, approvedBy: string];
      export interface OutputObject {claimId: bigint, approvedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimAuthorizedEvent {
      export type InputTuple = [claimId: BigNumberish, authorizedBy: AddressLike];
      export type OutputTuple = [claimId: bigint, authorizedBy: string];
      export interface OutputObject {claimId: bigint, authorizedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimRejectedEvent {
      export type InputTuple = [claimId: BigNumberish, reason: string, rejectedBy: AddressLike];
      export type OutputTuple = [claimId: bigint, reason: string, rejectedBy: string];
      export interface OutputObject {claimId: bigint, reason: string, rejectedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimSubmittedEvent {
      export type InputTuple = [claimId: BigNumberish, policyId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [claimId: bigint, policyId: bigint, amount: bigint];
      export interface OutputObject {claimId: bigint, policyId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyPausedEvent {
      export type InputTuple = [pausedBy: AddressLike];
      export type OutputTuple = [pausedBy: string];
      export interface OutputObject {pausedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyUnpausedEvent {
      export type InputTuple = [unpausedBy: AddressLike];
      export type OutputTuple = [unpausedBy: string];
      export interface OutputObject {unpausedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PayoutCompletedEvent {
      export type InputTuple = [claimId: BigNumberish, driver: AddressLike, amount: BigNumberish];
      export type OutputTuple = [claimId: bigint, driver: string, amount: bigint];
      export interface OutputObject {claimId: bigint, driver: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ClaimManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): ClaimManager;
    waitForDeployment(): Promise<this>;

    interface: ClaimManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    INSURANCE_COMPANY_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ORACLE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    approveClaim: TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    authorizeClaim: TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getClaim: TypedContractMethod<
      [claimId: BigNumberish, ],
      [InsuranceTypes.ClaimStructOutput],
      'view'
    >
    

    
    getPendingClaim: TypedContractMethod<
      [policyId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    insurancePolicy: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    insurancePool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isClaimRejected: TypedContractMethod<
      [claimId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    rejectClaim: TypedContractMethod<
      [claimId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitClaim: TypedContractMethod<
      [policyId: BigNumberish, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    submitClaimFor: TypedContractMethod<
      [driver: AddressLike, policyId: BigNumberish, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    verifyAccident: TypedContractMethod<
      [claimId: BigNumberish, isLegitimate: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'INSURANCE_COMPANY_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ORACLE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'approveClaim'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizeClaim'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getClaim'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [InsuranceTypes.ClaimStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingClaim'): TypedContractMethod<
      [policyId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'insurancePolicy'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'insurancePool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isClaimRejected'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'rejectClaim'): TypedContractMethod<
      [claimId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitClaim'): TypedContractMethod<
      [policyId: BigNumberish, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitClaimFor'): TypedContractMethod<
      [driver: AddressLike, policyId: BigNumberish, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyAccident'): TypedContractMethod<
      [claimId: BigNumberish, isLegitimate: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ClaimApproved'): TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
getEvent(key: 'ClaimAuthorized'): TypedContractEvent<ClaimAuthorizedEvent.InputTuple, ClaimAuthorizedEvent.OutputTuple, ClaimAuthorizedEvent.OutputObject>;
getEvent(key: 'ClaimRejected'): TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
getEvent(key: 'ClaimSubmitted'): TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
getEvent(key: 'EmergencyPaused'): TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
getEvent(key: 'EmergencyUnpaused'): TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PayoutCompleted'): TypedContractEvent<PayoutCompletedEvent.InputTuple, PayoutCompletedEvent.OutputTuple, PayoutCompletedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'ClaimApproved(uint256,address)': TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
      ClaimApproved: TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
    

      'ClaimAuthorized(uint256,address)': TypedContractEvent<ClaimAuthorizedEvent.InputTuple, ClaimAuthorizedEvent.OutputTuple, ClaimAuthorizedEvent.OutputObject>;
      ClaimAuthorized: TypedContractEvent<ClaimAuthorizedEvent.InputTuple, ClaimAuthorizedEvent.OutputTuple, ClaimAuthorizedEvent.OutputObject>;
    

      'ClaimRejected(uint256,string,address)': TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
      ClaimRejected: TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
    

      'ClaimSubmitted(uint256,uint256,uint256)': TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
      ClaimSubmitted: TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
    

      'EmergencyPaused(address)': TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
      EmergencyPaused: TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
    

      'EmergencyUnpaused(address)': TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
      EmergencyUnpaused: TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PayoutCompleted(uint256,address,uint256)': TypedContractEvent<PayoutCompletedEvent.InputTuple, PayoutCompletedEvent.OutputTuple, PayoutCompletedEvent.OutputObject>;
      PayoutCompleted: TypedContractEvent<PayoutCompletedEvent.InputTuple, PayoutCompletedEvent.OutputTuple, PayoutCompletedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }