/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'InsurancePool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.InsurancePool__factory>
getContractFactory(name: 'DriverRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DriverRegistry__factory>
getContractFactory(name: 'InsurancePolicy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.InsurancePolicy__factory>
getContractFactory(name: 'SafetyScoreOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SafetyScoreOracle__factory>
getContractFactory(name: 'ClaimManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ClaimManager__factory>
getContractFactory(name: 'InsuranceEvents', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.InsuranceEvents__factory>

  getContractAt(name: 'InsurancePool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.InsurancePool>
getContractAt(name: 'DriverRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DriverRegistry>
getContractAt(name: 'InsurancePolicy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.InsurancePolicy>
getContractAt(name: 'SafetyScoreOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SafetyScoreOracle>
getContractAt(name: 'ClaimManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ClaimManager>
getContractAt(name: 'InsuranceEvents', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.InsuranceEvents>

  deployContract(name: 'InsurancePool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InsurancePool>
deployContract(name: 'DriverRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DriverRegistry>
deployContract(name: 'InsurancePolicy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InsurancePolicy>
deployContract(name: 'SafetyScoreOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafetyScoreOracle>
deployContract(name: 'ClaimManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ClaimManager>
deployContract(name: 'InsuranceEvents', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InsuranceEvents>

  deployContract(name: 'InsurancePool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InsurancePool>
deployContract(name: 'DriverRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DriverRegistry>
deployContract(name: 'InsurancePolicy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InsurancePolicy>
deployContract(name: 'SafetyScoreOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafetyScoreOracle>
deployContract(name: 'ClaimManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ClaimManager>
deployContract(name: 'InsuranceEvents', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InsuranceEvents>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  