/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace InsuranceTypes {
      
    export type PolicyStruct = {id: BigNumberish, driver: AddressLike, premium: BigNumberish, coverage: BigNumberish, startTime: BigNumberish, expiryTime: BigNumberish, active: boolean, underReview: boolean}

    export type PolicyStructOutput = [id: bigint, driver: string, premium: bigint, coverage: bigint, startTime: bigint, expiryTime: bigint, active: boolean, underReview: boolean] & {id: bigint, driver: string, premium: bigint, coverage: bigint, startTime: bigint, expiryTime: bigint, active: boolean, underReview: boolean }
  
    }

  export interface InsurancePolicyInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "DURATION_30_DAYS" | "DURATION_7_DAYS" | "DURATION_90_DAYS" | "INSURANCE_COMPANY_ROLE" | "PAUSER_ROLE" | "cancelPolicy" | "driverRegistry" | "getPolicy" | "getRoleAdmin" | "grantRole" | "hasRole" | "insurancePool" | "isPolicyActive" | "pause" | "paused" | "purchasePolicy" | "purchasePolicyFor" | "renewPolicy" | "renounceRole" | "revokeRole" | "safetyScoreOracle" | "supportsInterface" | "unpause" | "updatePremium"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EmergencyPaused" | "EmergencyUnpaused" | "Paused" | "PolicyCancelled" | "PolicyPurchased" | "PolicyRenewed" | "PremiumUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DURATION_30_DAYS', values?: undefined): string;
encodeFunctionData(functionFragment: 'DURATION_7_DAYS', values?: undefined): string;
encodeFunctionData(functionFragment: 'DURATION_90_DAYS', values?: undefined): string;
encodeFunctionData(functionFragment: 'INSURANCE_COMPANY_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelPolicy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'driverRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPolicy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'insurancePool', values?: undefined): string;
encodeFunctionData(functionFragment: 'isPolicyActive', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'purchasePolicy', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'purchasePolicyFor', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renewPolicy', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'safetyScoreOracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updatePremium', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DURATION_30_DAYS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DURATION_7_DAYS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DURATION_90_DAYS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'INSURANCE_COMPANY_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'driverRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'insurancePool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPolicyActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purchasePolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purchasePolicyFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renewPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safetyScoreOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePremium', data: BytesLike): Result;
  }

  
    export namespace EmergencyPausedEvent {
      export type InputTuple = [pausedBy: AddressLike];
      export type OutputTuple = [pausedBy: string];
      export interface OutputObject {pausedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyUnpausedEvent {
      export type InputTuple = [unpausedBy: AddressLike];
      export type OutputTuple = [unpausedBy: string];
      export interface OutputObject {unpausedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyCancelledEvent {
      export type InputTuple = [policyId: BigNumberish, cancelledBy: AddressLike];
      export type OutputTuple = [policyId: bigint, cancelledBy: string];
      export interface OutputObject {policyId: bigint, cancelledBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyPurchasedEvent {
      export type InputTuple = [policyId: BigNumberish, driver: AddressLike, premium: BigNumberish, coverage: BigNumberish, expiryTime: BigNumberish];
      export type OutputTuple = [policyId: bigint, driver: string, premium: bigint, coverage: bigint, expiryTime: bigint];
      export interface OutputObject {policyId: bigint, driver: string, premium: bigint, coverage: bigint, expiryTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyRenewedEvent {
      export type InputTuple = [policyId: BigNumberish, newPremium: BigNumberish, newExpiryTime: BigNumberish];
      export type OutputTuple = [policyId: bigint, newPremium: bigint, newExpiryTime: bigint];
      export interface OutputObject {policyId: bigint, newPremium: bigint, newExpiryTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PremiumUpdatedEvent {
      export type InputTuple = [policyId: BigNumberish, oldPremium: BigNumberish, newPremium: BigNumberish];
      export type OutputTuple = [policyId: bigint, oldPremium: bigint, newPremium: bigint];
      export interface OutputObject {policyId: bigint, oldPremium: bigint, newPremium: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface InsurancePolicy extends BaseContract {
    
    connect(runner?: ContractRunner | null): InsurancePolicy;
    waitForDeployment(): Promise<this>;

    interface: InsurancePolicyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DURATION_30_DAYS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DURATION_7_DAYS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DURATION_90_DAYS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    INSURANCE_COMPANY_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cancelPolicy: TypedContractMethod<
      [policyId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    driverRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getPolicy: TypedContractMethod<
      [policyId: BigNumberish, ],
      [InsuranceTypes.PolicyStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    insurancePool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isPolicyActive: TypedContractMethod<
      [policyId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    purchasePolicy: TypedContractMethod<
      [premium: BigNumberish, coverageAmount: BigNumberish, durationSeconds: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    purchasePolicyFor: TypedContractMethod<
      [driver: AddressLike, premium: BigNumberish, coverageAmount: BigNumberish, durationSeconds: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    renewPolicy: TypedContractMethod<
      [policyId: BigNumberish, newPremium: BigNumberish, durationSeconds: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    safetyScoreOracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updatePremium: TypedContractMethod<
      [policyId: BigNumberish, newPremium: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DURATION_30_DAYS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DURATION_7_DAYS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DURATION_90_DAYS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'INSURANCE_COMPANY_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancelPolicy'): TypedContractMethod<
      [policyId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'driverRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPolicy'): TypedContractMethod<
      [policyId: BigNumberish, ],
      [InsuranceTypes.PolicyStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'insurancePool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isPolicyActive'): TypedContractMethod<
      [policyId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'purchasePolicy'): TypedContractMethod<
      [premium: BigNumberish, coverageAmount: BigNumberish, durationSeconds: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'purchasePolicyFor'): TypedContractMethod<
      [driver: AddressLike, premium: BigNumberish, coverageAmount: BigNumberish, durationSeconds: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'renewPolicy'): TypedContractMethod<
      [policyId: BigNumberish, newPremium: BigNumberish, durationSeconds: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safetyScoreOracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePremium'): TypedContractMethod<
      [policyId: BigNumberish, newPremium: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EmergencyPaused'): TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
getEvent(key: 'EmergencyUnpaused'): TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PolicyCancelled'): TypedContractEvent<PolicyCancelledEvent.InputTuple, PolicyCancelledEvent.OutputTuple, PolicyCancelledEvent.OutputObject>;
getEvent(key: 'PolicyPurchased'): TypedContractEvent<PolicyPurchasedEvent.InputTuple, PolicyPurchasedEvent.OutputTuple, PolicyPurchasedEvent.OutputObject>;
getEvent(key: 'PolicyRenewed'): TypedContractEvent<PolicyRenewedEvent.InputTuple, PolicyRenewedEvent.OutputTuple, PolicyRenewedEvent.OutputObject>;
getEvent(key: 'PremiumUpdated'): TypedContractEvent<PremiumUpdatedEvent.InputTuple, PremiumUpdatedEvent.OutputTuple, PremiumUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'EmergencyPaused(address)': TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
      EmergencyPaused: TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
    

      'EmergencyUnpaused(address)': TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
      EmergencyUnpaused: TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PolicyCancelled(uint256,address)': TypedContractEvent<PolicyCancelledEvent.InputTuple, PolicyCancelledEvent.OutputTuple, PolicyCancelledEvent.OutputObject>;
      PolicyCancelled: TypedContractEvent<PolicyCancelledEvent.InputTuple, PolicyCancelledEvent.OutputTuple, PolicyCancelledEvent.OutputObject>;
    

      'PolicyPurchased(uint256,address,uint256,uint256,uint64)': TypedContractEvent<PolicyPurchasedEvent.InputTuple, PolicyPurchasedEvent.OutputTuple, PolicyPurchasedEvent.OutputObject>;
      PolicyPurchased: TypedContractEvent<PolicyPurchasedEvent.InputTuple, PolicyPurchasedEvent.OutputTuple, PolicyPurchasedEvent.OutputObject>;
    

      'PolicyRenewed(uint256,uint256,uint64)': TypedContractEvent<PolicyRenewedEvent.InputTuple, PolicyRenewedEvent.OutputTuple, PolicyRenewedEvent.OutputObject>;
      PolicyRenewed: TypedContractEvent<PolicyRenewedEvent.InputTuple, PolicyRenewedEvent.OutputTuple, PolicyRenewedEvent.OutputObject>;
    

      'PremiumUpdated(uint256,uint256,uint256)': TypedContractEvent<PremiumUpdatedEvent.InputTuple, PremiumUpdatedEvent.OutputTuple, PremiumUpdatedEvent.OutputObject>;
      PremiumUpdated: TypedContractEvent<PremiumUpdatedEvent.InputTuple, PremiumUpdatedEvent.OutputTuple, PremiumUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }