// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface InsuranceTypes$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "InsuranceTypes";
  readonly sourceName: "contracts/libraries/InsuranceTypes.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212200d4129fd3dc8b48d7539283c6a119b311c1d9af1646ed6e22ee43d39eab0865964736f6c634300081e0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212200d4129fd3dc8b48d7539283c6a119b311c1d9af1646ed6e22ee43d39eab0865964736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/InsuranceTypes.sol";
  readonly buildInfoId: "solc-0_8_30-4a3112c1113d0cca2ad6553f2bdb311130dccbae";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["InsuranceTypes"]: InsuranceTypes$Type;
    ["contracts/libraries/InsuranceTypes.sol:InsuranceTypes"]: InsuranceTypes$Type;
  }
}