/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../common.js"
  

  export interface InsuranceEventsInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "ClaimApproved" | "ClaimRejected" | "ClaimSubmitted" | "DriverRegistered" | "EmergencyPaused" | "EmergencyUnpaused" | "FundsDeposited" | "PayoutCompleted" | "PolicyCancelled" | "PolicyPurchased" | "PolicyRenewed" | "PremiumUpdated" | "SafetyScoreUpdated"): EventFragment;

    

    
  }

  
    export namespace ClaimApprovedEvent {
      export type InputTuple = [claimId: BigNumberish, approvedBy: AddressLike];
      export type OutputTuple = [claimId: bigint, approvedBy: string];
      export interface OutputObject {claimId: bigint, approvedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimRejectedEvent {
      export type InputTuple = [claimId: BigNumberish, reason: string, rejectedBy: AddressLike];
      export type OutputTuple = [claimId: bigint, reason: string, rejectedBy: string];
      export interface OutputObject {claimId: bigint, reason: string, rejectedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimSubmittedEvent {
      export type InputTuple = [claimId: BigNumberish, policyId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [claimId: bigint, policyId: bigint, amount: bigint];
      export interface OutputObject {claimId: bigint, policyId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DriverRegisteredEvent {
      export type InputTuple = [wallet: AddressLike, driverId: BytesLike];
      export type OutputTuple = [wallet: string, driverId: string];
      export interface OutputObject {wallet: string, driverId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyPausedEvent {
      export type InputTuple = [pausedBy: AddressLike];
      export type OutputTuple = [pausedBy: string];
      export interface OutputObject {pausedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyUnpausedEvent {
      export type InputTuple = [unpausedBy: AddressLike];
      export type OutputTuple = [unpausedBy: string];
      export interface OutputObject {unpausedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsDepositedEvent {
      export type InputTuple = [depositor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [depositor: string, amount: bigint];
      export interface OutputObject {depositor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PayoutCompletedEvent {
      export type InputTuple = [claimId: BigNumberish, driver: AddressLike, amount: BigNumberish];
      export type OutputTuple = [claimId: bigint, driver: string, amount: bigint];
      export interface OutputObject {claimId: bigint, driver: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyCancelledEvent {
      export type InputTuple = [policyId: BigNumberish, cancelledBy: AddressLike];
      export type OutputTuple = [policyId: bigint, cancelledBy: string];
      export interface OutputObject {policyId: bigint, cancelledBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyPurchasedEvent {
      export type InputTuple = [policyId: BigNumberish, driver: AddressLike, premium: BigNumberish, coverage: BigNumberish, expiryTime: BigNumberish];
      export type OutputTuple = [policyId: bigint, driver: string, premium: bigint, coverage: bigint, expiryTime: bigint];
      export interface OutputObject {policyId: bigint, driver: string, premium: bigint, coverage: bigint, expiryTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyRenewedEvent {
      export type InputTuple = [policyId: BigNumberish, newPremium: BigNumberish, newExpiryTime: BigNumberish];
      export type OutputTuple = [policyId: bigint, newPremium: bigint, newExpiryTime: bigint];
      export interface OutputObject {policyId: bigint, newPremium: bigint, newExpiryTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PremiumUpdatedEvent {
      export type InputTuple = [policyId: BigNumberish, oldPremium: BigNumberish, newPremium: BigNumberish];
      export type OutputTuple = [policyId: bigint, oldPremium: bigint, newPremium: bigint];
      export interface OutputObject {policyId: bigint, oldPremium: bigint, newPremium: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SafetyScoreUpdatedEvent {
      export type InputTuple = [driver: AddressLike, newScore: BigNumberish];
      export type OutputTuple = [driver: string, newScore: bigint];
      export interface OutputObject {driver: string, newScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface InsuranceEvents extends BaseContract {
    
    connect(runner?: ContractRunner | null): InsuranceEvents;
    waitForDeployment(): Promise<this>;

    interface: InsuranceEventsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'ClaimApproved'): TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
getEvent(key: 'ClaimRejected'): TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
getEvent(key: 'ClaimSubmitted'): TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
getEvent(key: 'DriverRegistered'): TypedContractEvent<DriverRegisteredEvent.InputTuple, DriverRegisteredEvent.OutputTuple, DriverRegisteredEvent.OutputObject>;
getEvent(key: 'EmergencyPaused'): TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
getEvent(key: 'EmergencyUnpaused'): TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
getEvent(key: 'FundsDeposited'): TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
getEvent(key: 'PayoutCompleted'): TypedContractEvent<PayoutCompletedEvent.InputTuple, PayoutCompletedEvent.OutputTuple, PayoutCompletedEvent.OutputObject>;
getEvent(key: 'PolicyCancelled'): TypedContractEvent<PolicyCancelledEvent.InputTuple, PolicyCancelledEvent.OutputTuple, PolicyCancelledEvent.OutputObject>;
getEvent(key: 'PolicyPurchased'): TypedContractEvent<PolicyPurchasedEvent.InputTuple, PolicyPurchasedEvent.OutputTuple, PolicyPurchasedEvent.OutputObject>;
getEvent(key: 'PolicyRenewed'): TypedContractEvent<PolicyRenewedEvent.InputTuple, PolicyRenewedEvent.OutputTuple, PolicyRenewedEvent.OutputObject>;
getEvent(key: 'PremiumUpdated'): TypedContractEvent<PremiumUpdatedEvent.InputTuple, PremiumUpdatedEvent.OutputTuple, PremiumUpdatedEvent.OutputObject>;
getEvent(key: 'SafetyScoreUpdated'): TypedContractEvent<SafetyScoreUpdatedEvent.InputTuple, SafetyScoreUpdatedEvent.OutputTuple, SafetyScoreUpdatedEvent.OutputObject>;

    filters: {
      
      'ClaimApproved(uint256,address)': TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
      ClaimApproved: TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
    

      'ClaimRejected(uint256,string,address)': TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
      ClaimRejected: TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
    

      'ClaimSubmitted(uint256,uint256,uint256)': TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
      ClaimSubmitted: TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
    

      'DriverRegistered(address,bytes32)': TypedContractEvent<DriverRegisteredEvent.InputTuple, DriverRegisteredEvent.OutputTuple, DriverRegisteredEvent.OutputObject>;
      DriverRegistered: TypedContractEvent<DriverRegisteredEvent.InputTuple, DriverRegisteredEvent.OutputTuple, DriverRegisteredEvent.OutputObject>;
    

      'EmergencyPaused(address)': TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
      EmergencyPaused: TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
    

      'EmergencyUnpaused(address)': TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
      EmergencyUnpaused: TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
    

      'FundsDeposited(address,uint256)': TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
      FundsDeposited: TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
    

      'PayoutCompleted(uint256,address,uint256)': TypedContractEvent<PayoutCompletedEvent.InputTuple, PayoutCompletedEvent.OutputTuple, PayoutCompletedEvent.OutputObject>;
      PayoutCompleted: TypedContractEvent<PayoutCompletedEvent.InputTuple, PayoutCompletedEvent.OutputTuple, PayoutCompletedEvent.OutputObject>;
    

      'PolicyCancelled(uint256,address)': TypedContractEvent<PolicyCancelledEvent.InputTuple, PolicyCancelledEvent.OutputTuple, PolicyCancelledEvent.OutputObject>;
      PolicyCancelled: TypedContractEvent<PolicyCancelledEvent.InputTuple, PolicyCancelledEvent.OutputTuple, PolicyCancelledEvent.OutputObject>;
    

      'PolicyPurchased(uint256,address,uint256,uint256,uint64)': TypedContractEvent<PolicyPurchasedEvent.InputTuple, PolicyPurchasedEvent.OutputTuple, PolicyPurchasedEvent.OutputObject>;
      PolicyPurchased: TypedContractEvent<PolicyPurchasedEvent.InputTuple, PolicyPurchasedEvent.OutputTuple, PolicyPurchasedEvent.OutputObject>;
    

      'PolicyRenewed(uint256,uint256,uint64)': TypedContractEvent<PolicyRenewedEvent.InputTuple, PolicyRenewedEvent.OutputTuple, PolicyRenewedEvent.OutputObject>;
      PolicyRenewed: TypedContractEvent<PolicyRenewedEvent.InputTuple, PolicyRenewedEvent.OutputTuple, PolicyRenewedEvent.OutputObject>;
    

      'PremiumUpdated(uint256,uint256,uint256)': TypedContractEvent<PremiumUpdatedEvent.InputTuple, PremiumUpdatedEvent.OutputTuple, PremiumUpdatedEvent.OutputObject>;
      PremiumUpdated: TypedContractEvent<PremiumUpdatedEvent.InputTuple, PremiumUpdatedEvent.OutputTuple, PremiumUpdatedEvent.OutputObject>;
    

      'SafetyScoreUpdated(address,uint8)': TypedContractEvent<SafetyScoreUpdatedEvent.InputTuple, SafetyScoreUpdatedEvent.OutputTuple, SafetyScoreUpdatedEvent.OutputObject>;
      SafetyScoreUpdated: TypedContractEvent<SafetyScoreUpdatedEvent.InputTuple, SafetyScoreUpdatedEvent.OutputTuple, SafetyScoreUpdatedEvent.OutputObject>;
    
    };
  }